### ISSUE TITLE
[On Hold] [Products] Items with many Publications slow to load

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#12] opened 2024-07-18 09:26 UTC
If you look at the list of items:

https://main--danaher-optimus--aemsites.hlx.page/en-us/search

If you pick out the pages with many publications then they are slower to load and the page speed is terrible.  I think this is due to the API call being huge.  I'm just listing this as an issue.

![image](https://github.com/user-attachments/assets/9c6fbb80-3529-4a6c-ae9e-096d540d9959)

**Comment by Rajesh-GSPANN** [comment] 2024-08-08 04:45
Started Looking into this - In mobile view content is consuming more space

**Comment by davidzochowski** [comment] 2024-08-08 14:15
The issue is that all 3000+ publications are part of the product object from Coveo and so when the query to Coveo is made, the returned object is very large compared to other products (2.4 MB). I'm not immediately sure what we can do about this.
I'm open to suggestions.

**Comment by Rajesh-GSPANN** [comment] 2024-08-08 14:33
Hi @davidzochowski ,
I would suggest we have different API calls.
Existing API to get the PDP details, in that we can have only 2 to 5 records of the publications and another API to get all the publications.
@rgravitvl @amlan18041996  @pardeepgera23 please add your suggestions if you have any.
We can have a schedule a call to discuss more on this if needed.

CC: @davenichols-DHLS  @Meenu-GSPANN

Thanks!

**Comment by davidzochowski** [comment] 2024-08-08 15:06
I don't know if we can get a subset of a field. Afaik, it is an all or nothing type of deal.
I have raised a ticket with Coveo to see if they have a solution for this. I will let you know what they come back with.

**Comment by Rajesh-GSPANN** [comment] 2024-08-14 04:29
Hi @davidzochowski ,
As you mentioned below,
We won't be able to get a subset of publications, it's an all or nothing thing. We could do 2 api calls however that would eat up our QPM if we were forced to have 2 api calls per pdp when this really only affects less than 1% of products. If we do this, we might want to do the same as we do with lsig and have cloudflare cache the call to prevent the spike in query usage.

Did you get a chance to discuss with @davenichols-DHLS . 
We can hop on a call and discuss further.

CC: @Meenu-GSPANN @pardeepgera23  @rgravitvl  @sharanagoudapatil  @shivangi1422  @venkateshamkeerthi

**Comment by Meenu-GSPANN** [comment] 2024-12-17 04:39
Closing the issue due to the design changed

**Closed by Meenu-GSPANN** 2024-12-17 04:39 UTC
